//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF01
{
    using System;
    
    public partial class DepartComplex
    {
        public string Name { get; set; }
        public byte[] Version { get; set; }
    }
}
