//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF01
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee2
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int DepartmentId { get; set; }
        public Nullable<decimal> Salary { get; set; }
    
        public virtual Department2 Department2 { get; set; }
    }
}
